### ISSUE TITLE
Module: Test and measure content

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/edu#8]
### Link to module

https://docs.google.com/document/d/1s97qXwUzN_3N19Rlk9WrJ2w2dNPUjQ4EkpRC3anTnYM/edit#heading=h.4pn7h8pvtfkp
### Detailed information

[18F Edu modules- content strategy and writing for digital service teams](https://docs.google.com/document/d/1mdAOYbXXXNjOZmbSrihEgPshOYsPR1KNBU2tpAvIaaM/edit#)

**How to test and measure content:** How does one identify great content? While it might be easy to lean on Justice Potter Stewart’s famous mantra, “I know it when I see it,” a number of tools exist to help us determine if our content is performing the way we hope. 

Whether you’re a visual designer or a full stack developer, it’s likely the tools and websites you’re creating are filled with words. In this module, we’ll show you how to test those words, both through usability research and objective measurement.  
### Audience

Check all that apply:
- [ ] General
- [x] Trade specific
- [x] All levels
- [ ] Beginner
- [ ] Intermediate
- [ ] Advanced
### Tasks to completion
- [ ] Draft module
- [ ] Team edits and approval
- [ ] Implement

**Comment by mbland** [comment]
Just about ready to ship!
