### ISSUE TITLE
Module: Voice and tone

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/edu#9]
### Link to module

https://docs.google.com/document/d/1knWPy8PRKYRJ72tbGc9PHFqgO8Rq99JWT6IlpFkDKYg/edit#
### Detailed information

[18F Edu modules- content strategy and writing for digital service teams](https://docs.google.com/document/d/1mdAOYbXXXNjOZmbSrihEgPshOYsPR1KNBU2tpAvIaaM/edit#)

**Voice and tone:** If you’re like many folks, you might not be sure of the difference between voice and tone. Maybe you’ve never deliberately crafted a voice and don’t know where to start. Not to fret! In this tutorial, we’ll discuss the differences between voice and tone, how we describe our organizational voice, how to establish your own voice, and how to choose a tone that’s appropriate for whatever you’re writing.
### Audience

Check all that apply:
- [ ] General
- [ ] Trade specific
- [x] All levels
- [ ] Beginner
- [ ] Intermediate
- [ ] Advanced
### Tasks to completion
- [x] Draft module
- [ ] Team edits and approval
- [ ] Implement

**Comment by kategarklavs** [comment]
Shared link to this module in our Slack channel and am awaiting feedback from the team.

**Comment by kategarklavs** [comment]
(And for reference, here's the link to the module: https://docs.google.com/a/gsa.gov/document/d/1knWPy8PRKYRJ72tbGc9PHFqgO8Rq99JWT6IlpFkDKYg/edit?usp=sharing)
